{
  "stats": {
    "suites": 0,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2025-04-24T10:49:18.964Z",
    "end": "2025-04-24T10:49:19.162Z",
    "duration": 198,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "f787247c-b2dc-4b2c-bc90-ae3b9043941c",
      "title": "",
      "fullFile": "cypress/e2e/features/assignment_grading.feature",
      "file": "cypress/e2e/features/assignment_grading.feature",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [
        {
          "title": "An uncaught error was detected outside of a test",
          "fullTitle": "An uncaught error was detected outside of a test",
          "timedOut": null,
          "duration": 187,
          "state": "failed",
          "speed": null,
          "pass": false,
          "fail": true,
          "pending": false,
          "context": null,
          "code": "throw err;",
          "err": {
            "message": "Error: The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
            "estack": "Error: The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at createError (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:536:16)\n    at fail (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:540:15)\n    at assert (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:547:9)\n    at assertAndReturn (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:551:9)\n    at getRegistry (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:9571:49)\n    at defineBefore (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:10613:38)\n    at eval (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:11265:51)\n    at eval (http://localhost:8080/__cypress/tests?p=cypress/support/e2e.js:11278:3)\n    at eval (<anonymous>)",
            "diff": null
          },
          "uuid": "f86999aa-e664-40ca-a150-3747034987b1",
          "parentUUID": "f787247c-b2dc-4b2c-bc90-ae3b9043941c",
          "isHook": false,
          "skipped": false
        }
      ],
      "suites": [],
      "passes": [],
      "failures": [
        "f86999aa-e664-40ca-a150-3747034987b1"
      ],
      "pending": [],
      "skipped": [],
      "duration": 187,
      "root": true,
      "rootEmpty": false,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": {
        "id": "default",
        "reportDir": "cypress/reports/mocha",
        "overwrite": false,
        "html": false,
        "json": true
      },
      "version": "6.2.0"
    }
  }
}