{
  "specName": "assignment_creation.feature",
  "testName": "Creating an assignment with a very long description",
  "testState": "failed",
  "testError": "`cy.request()` failed trying to load:\n\nhttp://localhost:8080/test-utils/reset-database\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:8080/test-utils/reset-database\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n\nhttps://on.cypress.io/request",
  "testStack": "CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/test-utils/reset-database\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:8080/test-utils/reset-database\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n\nhttps://on.cypress.io/request\n    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:132388:70)\n    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)\n    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:4203:37)\n    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)\n    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)\n    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)\n    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)\n    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)\n    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)\n    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)\nFrom Your Spec Code:\n    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:11991:12)\n    at Registry.runHook (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9264:31)\n    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10112:39)\n    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)\n    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10111:51)\n\nFrom Node.js Internals:\n  RequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n      at new r (<embedded>:1868:354814)\n      at ee.callback (<embedded>:1868:360815)\n      at e.callback.s.callback [as _callback] (<embedded>:1868:360261)\n      at s._callback.s.callback.s.callback (<embedded>:2086:91494)\n      at ee.emit (node:events:527:28)\n      at ee.onRequestError (<embedded>:2086:100436)\n      at ClientRequest.emit (node:events:539:35)\n      at Socket.socketErrorListener (node:_http_client:454:9)\n      at Socket.emit (node:events:527:28)\n      at emitErrorNT (node:internal/streams/destroy:157:8)\n      at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "timestamp": "2025-05-09T18-51-41.823Z"
}