<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.174" tests="6" failures="6">
  <testsuite name="Root Suite" timestamp="2025-04-24T11:06:26" tests="0" file="cypress/e2e/features/assignment_viewing.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Assignment Viewing" timestamp="2025-04-24T11:06:26" tests="6" time="5.143" failures="6">
    <testcase name="Assignment Viewing Viewing all assignments across enrolled schedules" time="0.000" classname="Viewing all assignments across enrolled schedules">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10771:12)
    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9255:48)
    at Object.fn (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10156:41)
    at runStepWithLogGroup (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9860:36)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignments organized by schedule" time="0.000" classname="Viewing assignments organized by schedule">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10771:12)
    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9255:48)
    at Object.fn (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10156:41)
    at runStepWithLogGroup (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9860:36)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Sorting assignments by due date" time="0.000" classname="Sorting assignments by due date">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10771:12)
    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9255:48)
    at Object.fn (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10156:41)
    at runStepWithLogGroup (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9860:36)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignments by completion status" time="0.000" classname="Viewing assignments by completion status">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10771:12)
    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9255:48)
    at Object.fn (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10156:41)
    at runStepWithLogGroup (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9860:36)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignment details" time="0.000" classname="Viewing assignment details">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10771:12)
    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9255:48)
    at Object.fn (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10156:41)
    at runStepWithLogGroup (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9860:36)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignments with approaching deadlines" time="0.000" classname="Viewing assignments with approaching deadlines">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/assignments

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10771:12)
    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9255:48)
    at Object.fn (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10156:41)
    at runStepWithLogGroup (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9860:36)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10153:60)]]></failure>
    </testcase>
  </testsuite>
</testsuites>