<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="9.497" tests="5" failures="5">
  <testsuite name="Root Suite" timestamp="2025-05-09T17:56:58" tests="0" file="cypress/e2e/features/assignment_creation.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Assignment Creation" timestamp="2025-05-09T17:56:58" tests="5" time="9.427" failures="5">
    <testcase name="Assignment Creation Successfully creating an assignment with required fields" time="0.000" classname="Successfully creating an assignment with required fields">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:3001/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10925:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Attempting to create an assignment without required fields" time="0.000" classname="Attempting to create an assignment without required fields">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:3001/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10925:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Creating an assignment with file attachments" time="0.000" classname="Creating an assignment with file attachments">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:3001/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10925:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Creating an assignment with a past due date" time="0.000" classname="Creating an assignment with a past due date">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:3001/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10925:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Creating an assignment with a very long description" time="0.000" classname="Creating an assignment with a very long description">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:3001/assignments/create

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:3001/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10925:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
  </testsuite>
</testsuites>